mysql-server:
    container_name: mysql-server
    image: mysql
    volumes:
    - ${PWD}/startup:/docker-entrypoint-initdb.d
    - ${PWD}/data:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root

jetty-server:
    container_name: jetty-server
    image: jetty
    volumes:
    - ${PWD}/target:/var/lib/jetty/webapps
    ports:
    - 8080:8080
    - 443:8443
    links:
    - mysql-server:mysql-server